### ISSUE TITLE
Step3: Linked src files and Reading negatives edges

### ISSUE THREAD

**Issue by codeSG** [codeSG/pgrouting#8]
**Tasks**

1. Create src & include files for dealing negative edges with pgr_bellmanFord
    - [x] Create src/[bellman_ford_neg.c](https://github.com/codeSG/pgrouting/blob/bf-negative/src/bellman_ford/bellman_ford_neg.c)
    - [x] Create src/[bellman_ford_neg_driver.cpp](https://github.com/codeSG/pgrouting/blob/bf-negative/src/bellman_ford/bellman_ford_neg_driver.cpp)
    - [x] Create include/drivers/[bellman_ford_neg_driver.h](https://github.com/codeSG/pgrouting/blob/bf-negative/include/drivers/bellman_ford/bellman_ford_neg_driver.h)

2. Function to read negative_edge_sql
      - [x] Function to add a negative cost edge : [graph_add_neg_edge()](https://github.com/codeSG/pgrouting/blob/bf-negative/include/cpp_common/pgr_base_graph.hpp#L918)
      - [x] Function called by pgr_bellman_hpp [(Here)](https://github.com/codeSG/pgrouting/blob/bf-negative/src/bellman_ford/bellman_ford_neg_driver.cpp#L120) : [insert_negative_edges()](https://github.com/codeSG/pgrouting/blob/bf-negative/include/cpp_common/pgr_base_graph.hpp#L404)
